### ISSUE TITLE
Load wind turbine config from local path

### ISSUE THREAD

**Issue by fneum** [PyPSA/atlite#227]

**Comment by LukasFrankenQ** [comment]
Hi @fneum, thanks for the suggestion!

This is a small change and is currently worked on.

Looking at `atlite/resource.py`, it appears like the same improvements could be made in methods `get_solarpanelconfig` and `get_cspinstallationconfig`. Any reasons against this? Otherwise I would go ahead, and include it in the PR.

Should be merged by mid-August.

Cheers! :)
Lukas

**Comment by fneum** [comment]
Sure, would be a good addition and I don’t think anyone is already working on it.
