### ISSUE TITLE
Wrong coordinates and broken values in SARAH cutouts

### ISSUE THREAD

**Issue by euronion** [PyPSA/atlite#62]
The coordinates in SARAH cutouts are messed up, i.e. mirrored, see the image below.

![image](https://user-images.githubusercontent.com/42553970/79944313-7ce57100-846b-11ea-8316-01e2a1513a8e.png)

```
> albedo
<xarray.DataArray 'albedo' (y: 160, x: 270)>
array([[0.04827 , 0.048171, 0.048043, ..., 0.103032, 0.104033, 0.104248],
       [0.047978, 0.047966, 0.047898, ..., 0.104392, 0.109037, 0.11042 ],
       [0.047583, 0.04764 , 0.047696, ..., 0.105399, 0.109951, 0.111676],
       ...,
       [0.03567 , 0.03552 , 0.035488, ..., 0.353771, 0.35935 , 0.36295 ],
       [0.035606, 0.035525, 0.035507, ..., 0.356749, 0.357823, 0.359936],
       [0.035569, 0.0355  , 0.035465, ..., 0.360018, 0.361162, 0.359274]],
      dtype=float32)
Coordinates:
    time     datetime64[ns] 2013-06-01T12:00:00
  * x        (x) float64 -12.0 -11.8 -11.6 -11.4 -11.2 ... 41.2 41.4 41.6 41.8
  * y        (y) float64 33.0 33.2 33.4 33.6 33.8 ... 64.0 64.2 64.4 64.6 64.8
    lon      (x) float64 -12.0 -11.8 -11.6 -11.4 -11.2 ... 41.2 41.4 41.6 41.8
    lat      (y) float64 33.0 33.2 33.4 33.6 33.8 ... 64.0 64.2 64.4 64.6 64.8
Attributes:
    units:      (0 - 1)
    long_name:  Albedo
```

The cutout

```
> cutout
<Cutout europe-2013-sarah x=-12.00-41.80 y=33.00-64.80 time=2013-01-01-2013-12-31 prepared_features=['temperature', 'influx'] is_view=False>
```

with the messed up coordinates
```
> cutout.data
<xarray.Dataset>
Dimensions:         (time: 8760, x: 270, y: 160)
Coordinates:
  * time            (time) datetime64[ns] 2013-01-01 ... 2013-12-31T23:00:00
  * x               (x) float64 -12.0 -11.8 -11.6 -11.4 ... 41.2 41.4 41.6 41.8
  * y               (y) float64 33.0 33.2 33.4 33.6 33.8 ... 64.2 64.4 64.6 64.8
    lon             (x) float64 -12.0 -11.8 -11.6 -11.4 ... 41.2 41.4 41.6 41.8
    lat             (y) float64 33.0 33.2 33.4 33.6 33.8 ... 64.2 64.4 64.6 64.8
Data variables:
    temperature     (time, y, x) float32 ...
    influx_toa      (time, y, x) float32 ...
    albedo          (time, y, x) float32 ...
    influx_direct   (time, y, x) float32 ...
    influx_diffuse  (time, y, x) float32 ...
Attributes:
    module:               sarah
    prepared_features:    ['temperature', 'influx']
    creation_parameters:  {'resolution': 0.2, 'x': slice(-12.0, 42.0, None), ...
```

Maybe an Australian PoV?

**Comment by euronion** [comment]
Addendum:
`albedo` is only choosen as an example. `temperature` and `influx_toa` are affected similarly. `influx_diffuse` and `influx_direct` have a different problem: All values are simply `nan`.

**Comment by euronion** [comment]
Update:
I recreated the cutout again to exclude problems during creation or from transfer / faulty input files.
Problems regarding coordinates persist.
The problem with `influx_diffuse` and `influx_direct` is a bit different from what I described earlier:
The values for both variables for January until including November are zero or `nan`. Only December has usable data in these variables.

**Comment by FabianHofmann** [comment]
The problem lays not directly in the sarah.py script but in the era5 script. The `albedo` and other influx variables are retrieved from `era5` even though when the module is set to `sarah` (which is kind of weird, but I think the intention is to have a complete dataset...) 

ERA5 datasets have reversed y axis, which is fixed in the standard prepare_cutout function during the merger of the empty cutout with coordinates only and the features. In the sarah.py script the axis is not double-checked and overwritten [here](https://github.com/PyPSA/atlite/blob/1409a02f159118570ce34133162c10ef63d89730/atlite/datasets/sarah.py#L132). 

An easy fix is to make a double check and correction in the era5.py script, by adding 
```
    ds = maybe_swap_spatial_dims(ds)
```
into the `_rename_and_clean_coords` function. This ensures the correct alignment of the datasets.
`maybe_swap_spatial_dims` is defined in `gis.py`
