### ISSUE TITLE
heat_demand with chunked datasets

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/atlite#79]
@coroa pointed out that the heat_demand might have problems when chunking (at least there were some issues with windows). A time shift in the time coordinates might lead to loosing values at the border of chunks. This seems to be no problem for dask arrays:

When looking at the results of chunked and non-chunked datasets, the result for `heat_demand` is exactly the same. 

![heat_demand_chunked](https://user-images.githubusercontent.com/19226431/83760852-d00b3000-a675-11ea-85a8-614aa0e078a0.png)

**Comment by FabianHofmann** [comment]
Here is the code, for reproducibility:

```python 
import atlite
import matplotlib.pyplot as plt
import geopandas as gpd
from pathlib import Path
import xarray as xr


pypsa_eur_dir = Path('/home/fabian/vres/py/pypsa-eur/')

chunked = atlite.Cutout('pypsa-eur.nc', chunks={'time':100})
non_chunked = atlite.Cutout('pypsa-eur.nc', chunks=None)

layout = xr.ones_like(chunked.data.height)
kwargs = dict(layout=layout, hour_shift=3)
heat_demand = xr.Dataset(dict(chunked = chunked.heat_demand(**kwargs),
                              non_chunked = non_chunked.heat_demand(**kwargs)))

fig, (ax1, ax2) = plt.subplots(2,1, sharex=True)
heat_demand.to_array(name='Total Heat Demand Europe').plot.line(x='time', ax=ax1)
(chunked.data.temperature.mean(['x', 'y']).resample(time='1D').mean() - 273)\
        .rename('T [°C]').plot.line(ax=ax2)
fig.tight_layout()
fig.savefig('heat_demand_chunked.png')
```

**Comment by coroa** [comment]
Just a small note to clarify: Atlite v0.0.2 or v0.2 before merging the `dask compatibility` PR by Fabian had the problem that when they were averaging over days with a active time-shift of f.ex. 2hrs, they would in each *window* see a day with only 22hrs at the beginning and additional day of 2hrs and computed averages over those. This introduced non-unique indices at the boundary as described in #6. One would have had to postprocess these manually by averaging the duplicate entries with the correct weights, ie. use `(2*left + 22*right) / 24` at each boundary.

The dask chunks know their neighbours and they seem to be combined correctly automatically, so that no postprocessing is necessary, anymore!
